version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    restart: unless-stopped
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./static:/usr/src/app/static
    expose:
      - "12345"  # Exposed internally to Docker network
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/src/app/static:ro
      - ./uploads:/usr/src/app/uploads:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge